name: Build Pull Request

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Running my job"
  e2e-tests:
    uses: ./.github/workflows/prepare-and-run-e2e-tests.yml # TODO: Remove and use the build-pr workflow
    secrets: inherit