name: Run e2e tests

on:
    workflow_call:

jobs:
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to local-env repository
        uses: actions/checkout@v4
        with:
          repository: onecx/onecx-local-env
      - name: Make .sh scripts executable
        run: |
          find . -name "*.sh" -exec chmod +x {} \;
      - name: Update /etc/hosts
        run: |
          echo '127.0.0.1   local-proxy' | sudo tee -a /etc/hosts
          echo '127.0.0.1   keycloak-app' | sudo tee -a /etc/hosts
          echo '127.0.0.1   pgadmin' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-shell-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-theme-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-theme-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-workspace-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-workspace-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-user-profile-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-user-profile-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-permission-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-permission-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-product-store-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-product-store-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-iam-kc-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-iam-bff' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-tenant-svc' | sudo tee -a /etc/hosts
          echo '127.0.0.1   onecx-tenant-bff' | sudo tee -a /etc/hosts
      - name: Check docker
        run: docker -v
      - name: Start Docker Compose
        run: docker compose up -d
      - name: Import initial data
        run: ./import-onecx.sh
