name: Run e2e tests

on:
  workflow_call:

# TODO: Run tests in order of definition in the input list
# TODO: Use product's target run-e2e-tests to run the tests
# - for this it could be usefull to use an artifact from the build
# - also install cypress package in products
jobs:
  run-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to workspace repository
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm install cypress --save-dev
      - name: Run Cypress tests
        run: npx cypress run --spec 'cypress/e2e/**/*.cy.ts'
