name: Test build tmp
on:
  workflow_dispatch:

jobs:
  store-artifact:
    name: Store e2e test artifact
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - uses: actions/upload-artifact@v7
          with:
            name: e2e-test-artifact
            path: |
                    integration-tests/e2e-tests/playwright
            retention-days: 1
            if-no-files-found: error

  build-e2e-image:
    name: Build & Push E2E Test Image
    needs: store-artifact    
    permissions:
      contents: read
      packages: write
    uses: onecx/ci-common/.github/workflows/docker-build.yml@v1
    secrets: inherit
    with: 
      buildx: true
      platform: 'linux/amd64,linux/arm64'
      tags: '{{ .Version }},{{ .Branch }}'
      push: true
      samoDockerFile: integration-tests/e2e-tests/playwright/workspace.Dockerfile
      artifact: e2e-test-artifact
    