name: Test build tmp
on:
  workflow_dispatch:

jobs:
  build-e2e-image:
    name: Build & Push E2E Test Image
    permissions:
      contents: read
      packages: write
    uses: onecx/ci-common/.github/workflows/docker-build.yml@v1
    secrets: inherit
    with: 
      buildx: true
      platform: 'linux/amd64,linux/arm64'
      tags: '{{ .Version }},{{ .Branch }}'
      push: true
      samoDockerFile: integration-tests/e2e-tests/playwright/workspace.Dockerfile
      artifact: ''
    